Name: fontconfig
Summary: Font configuration and customization library
Version: 2.8.0
Release: 1
Group: System/Libraries
License: MIT
URL: http://fontconfig.org
Sources:
    - http://fontconfig.org/release/fontconfig-%{version}.tar.gz
    - 25-no-bitmap-fedora.conf
    - 10-antialias.conf
    - 10-hinted.conf
Description: |
    Fontconfig is designed to locate fonts within the
    system and select them according to requirements specified by 
    applications.

RequiresPre:
    - freetype >= %{freetype_version}
    - coreutils
PkgConfigBR:
    - freetype2 >= %{freetype_version}
       
PkgBR:
    - gawk
    - expat-devel
    - perl
Conflicts:
# Hebrew fonts referenced in fonts.conf changed names in fonts-hebrew-0.100
    - fonts-hebrew < 0.100
# Conflict with pre-modular X fonts, because they moved and we 
# reference the new path in %%configure
    - fonts-xorg-base
    - fonts-xorg-syriac
Configure: configure
ConfigOptions:
    - --with-add-fonts=/usr/share/X11/fonts/Type1,/usr/share/X11/fonts/TTF,/usr/local/share/fonts
Builder: make
SubPackages:
    - Name: devel
      Summary: Font configuration and customization library
      Group: Development/Libraries
      Description: |
          The fontconfig-devel package includes the header files,
          and developer docs for the fontconfig package.
          
          Install fontconfig-devel if you want to develop programs which 
          will use fontconfig.
      Requires:
          - fontconfig = %{version}-%{release}
          - freetype-devel >= %{freetype_version}
          - pkgconfig

